version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres-1
    environment:
      POSTGRES_DB: baseauthdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
